// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgPZHzEv-SWX9JPDWx5en2TFRNVqsRCo',
    appId: '1:600269487466:web:d035d75b2b33c841fbb913',
    messagingSenderId: '600269487466',
    projectId: 'uas---ambw',
    authDomain: 'uas---ambw.firebaseapp.com',
    storageBucket: 'uas---ambw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvW75Q-r_4AlJDM-7ePnxaI8ylYUg4F0',
    appId: '1:600269487466:android:7f08d9ead14d05affbb913',
    messagingSenderId: '600269487466',
    projectId: 'uas---ambw',
    storageBucket: 'uas---ambw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2RUlmM7jFTQ4mNe-6CSP-X4X3jEf68E',
    appId: '1:600269487466:ios:9aa178a84aab9b20fbb913',
    messagingSenderId: '600269487466',
    projectId: 'uas---ambw',
    storageBucket: 'uas---ambw.appspot.com',
    iosClientId: '600269487466-5at5qpqj092jbbbbue37u35earnf4qod.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasAmbw',
  );
}
